"use client";

import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import type { LayoutFooter } from "../styled-doc-parts/types";

interface FooterEditorProps {
  footer: LayoutFooter;
  onChange: (footer: LayoutFooter) => void;
}

export function FooterEditor({ footer, onChange }: FooterEditorProps) {
  return (
    <div className="space-y-4">
      <div>
        <Label className="text-xs">Entity Name</Label>
        <Input
          value={footer.entity}
          onChange={(e) => onChange({ ...footer, entity: e.target.value })}
          className="h-8 text-xs mt-1"
        />
      </div>
      <div>
        <Label className="text-xs">NMLS #</Label>
        <Input
          value={footer.nmls ?? ""}
          onChange={(e) =>
            onChange({ ...footer, nmls: e.target.value || undefined })
          }
          placeholder="e.g. 2560918"
          className="h-8 text-xs mt-1"
        />
      </div>
      <div>
        <Label className="text-xs">Generated By Text</Label>
        <Input
          value={footer.generated_by ?? ""}
          onChange={(e) =>
            onChange({ ...footer, generated_by: e.target.value || undefined })
          }
          placeholder="e.g. Generated via RequityOS"
          className="h-8 text-xs mt-1"
        />
      </div>
      <div className="flex items-center gap-2">
        <Switch
          checked={footer.confidential ?? false}
          onCheckedChange={(checked) =>
            onChange({ ...footer, confidential: checked })
          }
        />
        <Label className="text-xs">Confidential notice</Label>
      </div>
    </div>
  );
}
