"use client";

import { useState, useMemo } from "react";
import Link from "next/link";
import {
  Search,
  MoreHorizontal,
  Download,
  Pencil,
  ExternalLink,
  XCircle,
} from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { StatusBadge } from "@/components/shared/status-badge";
import { formatDate } from "@/lib/format";

const TYPE_LABELS: Record<string, string> = {
  nda: "NDA",
  broker_agreement: "Broker Agreement",
  term_sheet: "Term Sheet",
  loan_agreement: "Loan Agreement",
  investor_agreement: "Investor Agreement",
  other: "Other",
};

const TYPE_COLORS: Record<string, string> = {
  nda: "bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-300",
  broker_agreement: "bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-300",
  term_sheet: "bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-300",
  loan_agreement: "bg-amber-100 text-amber-800 dark:bg-amber-900 dark:text-amber-300",
  investor_agreement: "bg-teal-100 text-teal-800 dark:bg-teal-900 dark:text-teal-300",
  other: "bg-gray-100 text-gray-800",
};

export interface GeneratedDocRow {
  id: string;
  file_name: string;
  template_name: string;
  template_type: string;
  record_type: string;
  record_id: string;
  status: string;
  generated_by_name: string;
  generated_at: string;
  gdrive_file_id: string | null;
}

interface Props {
  data: GeneratedDocRow[];
  action?: React.ReactNode;
}

export function GeneratedDocumentsTable({ data, action }: Props) {
  const [search, setSearch] = useState("");
  const [typeFilter, setTypeFilter] = useState("all");
  const [statusFilter, setStatusFilter] = useState("all");

  const filtered = useMemo(() => {
    let result = data;
    if (search) {
      const q = search.toLowerCase();
      result = result.filter(
        (d) =>
          d.file_name.toLowerCase().includes(q) ||
          d.template_name.toLowerCase().includes(q) ||
          d.generated_by_name.toLowerCase().includes(q)
      );
    }
    if (typeFilter !== "all") {
      result = result.filter((d) => d.template_type === typeFilter);
    }
    if (statusFilter !== "all") {
      result = result.filter((d) => d.status === statusFilter);
    }
    return result;
  }, [data, search, typeFilter, statusFilter]);

  const uniqueTypes = Array.from(new Set(data.map((d) => d.template_type)));
  const uniqueStatuses = Array.from(new Set(data.map((d) => d.status)));

  return (
    <div className="space-y-4">
      {/* Filters */}
      <div className="flex items-center gap-3">
        <div className="relative flex-1 max-w-xs">

          <Search
            size={14}
            className="absolute left-2.5 top-1/2 -translate-y-1/2 text-muted-foreground"
          />
          <Input
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search documents..."
            className="h-8 pl-8 text-xs"
          />
        </div>
        <Select value={typeFilter} onValueChange={setTypeFilter}>
          <SelectTrigger className="h-8 w-[160px] text-xs">
            <SelectValue placeholder="All Types" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All Types</SelectItem>
            {uniqueTypes.map((t) => (
              <SelectItem key={t} value={t}>
                {TYPE_LABELS[t] ?? t}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
        <Select value={statusFilter} onValueChange={setStatusFilter}>
          <SelectTrigger className="h-8 w-[160px] text-xs">
            <SelectValue placeholder="All Statuses" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All Statuses</SelectItem>
            {uniqueStatuses.map((s) => (
              <SelectItem key={s} value={s}>
                {s.replace(/_/g, " ")}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
        {action && <div className="ml-auto">{action}</div>}
      </div>

      {/* Table */}
      <div className="bg-card rounded-md border">
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b text-left text-muted-foreground">
                <th className="px-4 py-3 font-medium">Document</th>
                <th className="px-4 py-3 font-medium">Type</th>
                <th className="px-4 py-3 font-medium">Source</th>
                <th className="px-4 py-3 font-medium">Generated By</th>
                <th className="px-4 py-3 font-medium">Date</th>
                <th className="px-4 py-3 font-medium">Status</th>
                <th className="px-4 py-3 font-medium w-[60px]" />
              </tr>
            </thead>
            <tbody>
              {filtered.length === 0 && (
                <tr>
                  <td
                    colSpan={7}
                    className="px-4 py-12 text-center text-muted-foreground"
                  >
                    No generated documents found.
                  </td>
                </tr>
              )}
              {filtered.map((doc) => (
                <tr
                  key={doc.id}
                  className="border-b last:border-0 hover:bg-muted/50 transition-colors"
                >
                  <td className="px-4 py-3">
                    <Link
                      href={`/admin/documents/editor/${doc.id}`}
                      className="font-medium text-foreground hover:underline"
                    >
                      {doc.file_name}
                    </Link>
                  </td>
                  <td className="px-4 py-3">
                    <Badge
                      variant="secondary"
                      className={TYPE_COLORS[doc.template_type] ?? TYPE_COLORS.other}
                    >
                      {TYPE_LABELS[doc.template_type] ?? doc.template_type}
                    </Badge>
                  </td>
                  <td className="px-4 py-3 text-muted-foreground capitalize">
                    {doc.record_type}
                  </td>
                  <td className="px-4 py-3 text-muted-foreground">
                    {doc.generated_by_name}
                  </td>
                  <td className="px-4 py-3 text-muted-foreground num">
                    {formatDate(doc.generated_at)}
                  </td>
                  <td className="px-4 py-3">
                    <StatusBadge status={doc.status} />
                  </td>
                  <td className="px-4 py-3">
                    <DropdownMenu>
                      <DropdownMenuTrigger asChild>
                        <Button variant="ghost" size="icon" className="h-8 w-8">
                          <MoreHorizontal size={14} />
                        </Button>
                      </DropdownMenuTrigger>
                      <DropdownMenuContent align="end">
                        <DropdownMenuItem asChild>
                          <Link href={`/admin/documents/editor/${doc.id}`}>
                            <Pencil size={14} className="mr-2" />
                            Edit in Portal
                          </Link>
                        </DropdownMenuItem>
                        {doc.gdrive_file_id && (
                          <DropdownMenuItem
                            onClick={() =>
                              window.open(
                                `https://docs.google.com/document/d/${doc.gdrive_file_id}`,
                                "_blank"
                              )
                            }
                          >
                            <ExternalLink size={14} className="mr-2" />
                            Open in Drive
                          </DropdownMenuItem>
                        )}
                        <DropdownMenuItem>
                          <Download size={14} className="mr-2" />
                          Download
                        </DropdownMenuItem>
                      </DropdownMenuContent>
                    </DropdownMenu>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
