-- ============================================================
-- Draw Management Infrastructure — Functions
-- Applied via Supabase MCP as:
--   draw_management_validation_functions
--   draw_management_create_budget_function
--   draw_management_submit_draw_function
--   draw_management_approve_change_request_function
--   draw_management_approve_and_fund_draw_functions
--   draw_management_summary_functions
--   draw_management_loan_events_trigger
--   fix_portfolio_dashboard_borrower_name
-- ============================================================

-- See individual MCP migrations for full function bodies.
-- Functions created:
--   validate_budget_integrity(uuid) → boolean
--   validate_change_request_balance(uuid) → boolean
--   create_construction_budget(uuid, jsonb, uuid) → uuid
--   submit_draw_request(uuid, jsonb, text, uuid) → uuid
--   approve_budget_change_request(uuid, uuid) → jsonb
--   approve_draw_request(uuid, numeric, jsonb, uuid, text) → jsonb
--   fund_draw_request(uuid, date, numeric, text, uuid) → jsonb
--   get_draw_summary(uuid) → jsonb
--   get_portfolio_draw_dashboard() → jsonb
--   update_loan_draw_totals_from_event() → trigger function
