/**
 * Loan Request Form Definition
 * 
 * This is the quick loan request form for borrowers and brokers on the website.
 * This is the fast intake form - a full "Loan Application" comes later in the process.
 * 
 * To use this:
 * 1. Import this file
 * 2. Insert into form_definitions table via Control Center or migration
 */

import type { FormDefinition } from "./types";
import {
  LOAN_TYPES,
  RESIDENTIAL_TYPES,
  COMMERCIAL_TYPES,
  TIMELINES,
  EXPERIENCE_LEVELS,
  CREDIT_SCORE_RANGES,
  DEALS_24_MONTHS,
  CITIZENSHIP_OPTIONS,
} from "@repo/lib";

export const LOAN_APPLICATION_FORM: Omit<FormDefinition, "id" | "created_at" | "updated_at" | "created_by"> = {
  name: "Loan Request",
  slug: "loan-request",
  description: "Quick loan request form for borrowers and brokers with real-time pricing and term sheet generation",
  status: "published",
  mode: "both",
  contexts: ["external", "internal"],
  settings: {
    success_message: "Thank you for your application. Our team will review it and reach out within 24 hours.",
    notify_emails: [],
    token_expiry_days: 7,
  },
  steps: [
    // Step 1: Loan Type Selection (Router - auto-advances)
    {
      id: "loan_type",
      title: "What are you financing?",
      subtitle: "Select your loan type",
      type: "router",
      target_entity: null,
      match_on: null,
      show_when: null,
      fields: [
        {
          id: "loan_type",
          type: "card-select",
          label: null,
          required: true,
          mapped_column: null,
          width: "full",
          placeholder: null,
          visibility_mode: "both",
          visibility_form_mode: "both",
          options: [
            // Commercial types
            ...COMMERCIAL_TYPES.map((lt) => ({
              value: lt.id,
              label: lt.label,
              description: lt.desc,
              icon: undefined,
            })),
            // Residential types
            ...RESIDENTIAL_TYPES.map((lt) => ({
              value: lt.id,
              label: lt.label,
              description: lt.desc,
              icon: undefined,
            })),
          ],
        },
      ],
    },

    // Step 2: Property Address
    {
      id: "property_address",
      title: "Where is the property?",
      subtitle: "Enter the property address",
      type: "form",
      target_entity: "property",
      match_on: null,
      show_when: null,
      fields: [
        {
          id: "property_address",
          type: "custom",
          label: "Property Address",
          required: true,
          mapped_column: "address_line1",
          width: "full",
          placeholder: "Enter property address...",
          visibility_mode: "both",
          visibility_form_mode: "both",
          component_type: "google-places",
          component_config: {
            address_field: "property_address",
            city_field: "city",
            state_field: "state",
            zip_field: "zip",
          },
        },
      ],
    },

    // Step 3: Deal Sizing
    {
      id: "deal_sizing",
      title: "Size your deal",
      subtitle: "Enter purchase price, rehab budget, and loan amount",
      type: "form",
      target_entity: "opportunity",
      match_on: null,
      show_when: null,
      fields: [
        {
          id: "purchase_price",
          type: "custom",
          label: "Purchase Price",
          required: true,
          mapped_column: "purchase_price",
          width: "half",
          placeholder: "$0",
          visibility_mode: "both",
          visibility_form_mode: "both",
          component_type: "thousands-currency",
        },
        {
          id: "rehab_budget",
          type: "custom",
          label: "Rehab Budget",
          required: false,
          mapped_column: "rehab_budget",
          width: "half",
          placeholder: "$0",
          visibility_mode: "both",
          visibility_form_mode: "both",
          component_type: "thousands-currency",
        },
        {
          id: "after_repair_value",
          type: "custom",
          label: "After Repair Value (ARV)",
          required: false,
          mapped_column: "after_repair_value",
          width: "half",
          placeholder: "$0",
          visibility_mode: "both",
          visibility_form_mode: "both",
          component_type: "thousands-currency",
        },
        {
          id: "timeline",
          type: "select",
          label: "Timeline to Close",
          required: false,
          mapped_column: "timeline_to_close",
          width: "half",
          placeholder: "Select Timeline",
          visibility_mode: "both",
          visibility_form_mode: "both",
          options: TIMELINES.map((t) => ({
            value: t,
            label: t,
          })),
        },
        {
          id: "loan_amount",
          type: "custom",
          label: "Loan Amount",
          required: true,
          mapped_column: "loan_amount_requested",
          width: "full",
          placeholder: null,
          visibility_mode: "both",
          visibility_form_mode: "both",
          component_type: "loan-amount-slider",
          component_config: {
            min: 50,
            max: 90,
            default: 75,
            purchase_price_field: "purchase_price",
            rehab_budget_field: "rehab_budget",
            arv_field: "after_repair_value",
          },
        },
        {
          id: "pricing_calculator",
          type: "custom",
          label: null,
          required: false,
          mapped_column: null,
          width: "full",
          placeholder: null,
          visibility_mode: "both",
          visibility_form_mode: "both",
          component_type: "pricing-calculator",
          component_config: {
            loan_type_field: "loan_type",
            credit_score_field: "credit_score",
            deals_24_months_field: "deals_in_last_24_months",
            citizenship_field: "citizenship_status",
            purchase_price_field: "purchase_price",
            rehab_budget_field: "rehab_budget",
            arv_field: "after_repair_value",
            loan_amount_field: "loan_amount",
          },
        },
      ],
    },

    // Step 4: Borrower Profile (conditional - only for loan types with auto-terms)
    {
      id: "borrower_profile",
      title: "Your borrower profile",
      subtitle: "This determines your loan program and rate",
      type: "form",
      target_entity: "borrower",
      match_on: null,
      show_when: [
        {
          field: "loan_type",
          op: "in",
          value: [
            "Fix & Flip",
            "DSCR Rental",
            "New Construction",
            "CRE Bridge",
            "Manufactured Housing",
            "RV Park",
            "Multifamily",
          ],
        },
      ],
      fields: [
        {
          id: "credit_score",
          type: "card-select",
          label: "Credit Score Range",
          required: true,
          mapped_column: "credit_score",
          width: "full",
          placeholder: null,
          visibility_mode: "both",
          visibility_form_mode: "both",
          options: CREDIT_SCORE_RANGES.map((cs) => ({
            value: cs,
            label: cs,
          })),
        },
        {
          id: "deals_in_last_24_months",
          type: "card-select",
          label: "Deals in Last 24 Months",
          required: true,
          mapped_column: "deals_in_last_24_months",
          width: "full",
          placeholder: null,
          visibility_mode: "both",
          visibility_form_mode: "both",
          options: DEALS_24_MONTHS.map((d) => ({
            value: d,
            label: d,
          })),
        },
        {
          id: "citizenship_status",
          type: "card-select",
          label: "Citizenship / Residency",
          required: true,
          mapped_column: "citizenship_status",
          width: "full",
          placeholder: null,
          visibility_mode: "both",
          visibility_form_mode: "both",
          options: CITIZENSHIP_OPTIONS.map((c) => ({
            value: c,
            label: c,
          })),
        },
      ],
    },

    // Step 5: Contact Information
    {
      id: "contact_info",
      title: "Almost there",
      subtitle: "Let us know how to reach you",
      type: "form",
      target_entity: "contact",
      match_on: "email",
      show_when: null,
      fields: [
        {
          id: "first_name",
          type: "text",
          label: "First Name",
          required: true,
          mapped_column: "first_name",
          width: "half",
          placeholder: "John",
          visibility_mode: "both",
          visibility_form_mode: "both",
        },
        {
          id: "last_name",
          type: "text",
          label: "Last Name",
          required: true,
          mapped_column: "last_name",
          width: "half",
          placeholder: "Smith",
          visibility_mode: "both",
          visibility_form_mode: "both",
        },
        {
          id: "email",
          type: "email",
          label: "Email",
          required: true,
          mapped_column: "email",
          width: "half",
          placeholder: "john@company.com",
          visibility_mode: "both",
          visibility_form_mode: "both",
        },
        {
          id: "phone",
          type: "phone",
          label: "Phone",
          required: true,
          mapped_column: "phone",
          width: "half",
          placeholder: "(813) 327-5180",
          visibility_mode: "both",
          visibility_form_mode: "both",
        },
        {
          id: "company",
          type: "text",
          label: "Company",
          required: false,
          mapped_column: "company_name",
          width: "half",
          placeholder: "Company Name",
          visibility_mode: "both",
          visibility_form_mode: "both",
        },
        {
          id: "experience_level",
          type: "select",
          label: "Experience Level",
          required: false,
          mapped_column: "experience_level",
          width: "half",
          placeholder: "Select Level",
          visibility_mode: "both",
          visibility_form_mode: "both",
          options: EXPERIENCE_LEVELS.map((e) => ({
            value: e,
            label: e,
          })),
        },
        {
          id: "stated_net_worth",
          type: "select",
          label: "Stated Net Worth",
          required: false,
          mapped_column: null,
          width: "half",
          placeholder: "Select Range",
          visibility_mode: "both",
          visibility_form_mode: "both",
          options: [
            { value: "Under $250K", label: "Under $250K" },
            { value: "$250K - $500K", label: "$250K - $500K" },
            { value: "$500K - $1M", label: "$500K - $1M" },
            { value: "$1M - $2.5M", label: "$1M - $2.5M" },
            { value: "$2.5M - $5M", label: "$2.5M - $5M" },
            { value: "$5M - $10M", label: "$5M - $10M" },
            { value: "$10M+", label: "$10M+" },
          ],
        },
        {
          id: "stated_liquidity",
          type: "select",
          label: "Stated Liquidity",
          required: false,
          mapped_column: null,
          width: "half",
          placeholder: "Select Range",
          visibility_mode: "both",
          visibility_form_mode: "both",
          options: [
            { value: "Under $50K", label: "Under $50K" },
            { value: "$50K - $100K", label: "$50K - $100K" },
            { value: "$100K - $250K", label: "$100K - $250K" },
            { value: "$250K - $500K", label: "$250K - $500K" },
            { value: "$500K - $1M", label: "$500K - $1M" },
            { value: "$1M - $2.5M", label: "$1M - $2.5M" },
            { value: "$2.5M+", label: "$2.5M+" },
          ],
        },
      ],
    },
  ],
};
