-- ============================================================
-- Draw Management Infrastructure — RLS Policies & Indexes
-- Applied via Supabase MCP as:
--   draw_management_rls_policies_admin_borrower
--   draw_management_rls_policies_draws_inspections_docs
--   draw_management_indexes
-- ============================================================

-- RLS Policies applied:
--   Admin full access on all 11 new tables
--   Borrower SELECT on own loan data (budgets, draws, line items, inspections, documents)
--   Borrower INSERT on draw_documents for own loans
--   Inspector SELECT/INSERT on assigned draw inspection reports and documents
--   Storage policies on draw-documents bucket

-- Indexes created:
--   idx_construction_budgets_loan_id
--   idx_budget_line_items_budget_id
--   idx_budget_line_items_loan_id
--   idx_budget_line_item_history_item_id
--   idx_budget_change_requests_budget_status
--   idx_draw_requests_loan_status
--   idx_draw_requests_active_status (partial index)
--   idx_draw_request_line_items_draw_id
--   idx_draw_request_line_items_budget_item
--   idx_inspection_reports_draw_id
--   idx_draw_documents_draw_id
--   idx_draw_documents_loan_type
--   idx_loan_events_loan_id
--   idx_loan_events_type
