import type { LoanType } from './database';

export const DOCUMENT_TEMPLATES: Record<string, string[]> = {
  'CRE Bridge': [
    'Purchase Contract or Refinance Package',
    'Entity Formation Documents (Articles, Operating Agreement)',
    'Borrower Financial Statement (PFS)',
    'Guarantor Government ID',
    'Property Insurance Certificate',
    'Phase I Environmental (if applicable)',
    'Appraisal / BPO',
    'Rent Roll (if applicable)',
    'T12 Operating Statement (if applicable)',
    'Title Commitment',
    'Survey',
  ],
  'Multifamily': [
    'Purchase Contract or Refinance Package',
    'Entity Formation Documents (Articles, Operating Agreement)',
    'Borrower Financial Statement (PFS)',
    'Guarantor Government ID',
    'Property Insurance Certificate',
    'Phase I Environmental (if applicable)',
    'Appraisal / BPO',
    'Rent Roll (if applicable)',
    'T12 Operating Statement (if applicable)',
    'Title Commitment',
    'Survey',
  ],
  'MHC': [
    'Purchase Contract or Refinance Package',
    'Entity Formation Documents (Articles, Operating Agreement)',
    'Borrower Financial Statement (PFS)',
    'Guarantor Government ID',
    'Property Insurance Certificate',
    'Phase I Environmental (if applicable)',
    'Appraisal / BPO',
    'Rent Roll (if applicable)',
    'T12 Operating Statement (if applicable)',
    'Title Commitment',
    'Survey',
  ],
  'RV Park': [
    'Purchase Contract or Refinance Package',
    'Entity Formation Documents (Articles, Operating Agreement)',
    'Borrower Financial Statement (PFS)',
    'Guarantor Government ID',
    'Property Insurance Certificate',
    'Phase I Environmental (if applicable)',
    'Appraisal / BPO',
    'Rent Roll (if applicable)',
    'T12 Operating Statement (if applicable)',
    'Title Commitment',
    'Survey',
  ],
  'Fix & Flip': [
    'Purchase Contract',
    'Scope of Work & Budget',
    'Entity Formation Documents',
    'Borrower Government ID',
    'Track Record / Experience Resume',
    'Property Insurance Certificate',
    'Contractor Information & Bids',
    'Title Commitment',
  ],
  'DSCR': [
    'Purchase Contract or Refinance Package',
    'Lease Agreement(s)',
    'Entity Formation Documents',
    'Borrower Government ID',
    'Property Insurance Certificate',
    'Appraisal',
    'Title Commitment',
  ],
  'New Construction': [
    'Purchase Contract (lot)',
    'Plans & Specifications',
    'Construction Budget',
    'Entity Formation Documents',
    'Builder License & Insurance',
    'General Contractor Agreement',
    'Environmental Reports',
    'Permits (or permit application)',
    'Title Commitment',
  ],
};

export function getTemplateForLoanType(loanType: LoanType): string[] {
  return DOCUMENT_TEMPLATES[loanType] || [];
}
